all:
	#cp ./PerlSquad/javascripts/preload_test.html "c:/Apache/htdocs"
	#cp ./PerlSquad/Pictures/Precipitation/Rainforest/Rain.jpg "c:/Apache/htdocs"
	cp PHPFileUploadtest.html c:/Apache/htdocs
run:
	httpd.exe
	